### ISSUE TITLE
lico-update.sh does not use https

### ISSUE THREAD

**Issue by samtygier** [alexloehner/linuxcounter-update-examples#3]
lico-update.sh submission is over plain http. It should be over https.
```
apiurl="http://api.linuxcounter.net/v1"
```

**Comment by alexloehner** [comment]
Hi there, thanks for your report.

Unfortunatly SSL certificates costs much money and I really don't have enough, to get a certificate for each my domains. The Linux Counter itself is already on SSL, but the API is not, that is right.
As long as I don't get enough donations for it, I'll not buy another certificate.  :)

**Comment by leeps** [comment]
SSL certs really don't cost much money anymore.
There are already several free options (though some do come with a bit of a hassle) and Let's Encrypt start in September.
Please reconsider this issue. Since curl supports SNI, you're fine even if you need to keep using your current certificate on the same machine

https://www.startssl.com/
https://buy.wosign.com/free/

**Comment by apiraino** [comment]
Hi,

sorry for some seriously necromancing on this issue - SSL certs are now [FREE since 2 years](https://letsencrypt.org/) and the renewal process cen be [completely automated](https://certbot.eff.org/).

Can we now have SSL on the API endpoint, pretty please? :-)
