### ISSUE TITLE
Machine-updatekey

### ISSUE THREAD

**Issue by Linux-Ham** [alexloehner/linuxcounter-update-examples#4]
I have installed Lico-update for Android on CM 12.1 and unable to enter the Machine-updatekey due to after entering the ID of the machine from my profile I am just left with a number pad and unable to enter the alphanumeric Machine-updatekey.

I have tried manually adding the Machine-updatekey to the /storage/emulated/data/com.linuxcounter.lico_update_003/.linuxcounter file but it still fails to show nor is it deleted from the said file either., as you can see from image below.

![screenshot_2015-05-24-11-34-13](https://cloud.githubusercontent.com/assets/583652/7786376/efd3d750-0208-11e5-9ac8-4862b4a1bb03.png)

![screenshot_2015-05-24-11-31-04](https://cloud.githubusercontent.com/assets/583652/7786374/a82ac7f6-0208-11e5-94f0-d4621dfcf87b.png)

**Comment by alexloehner** [comment]
Hello,

I've changed the format of these update keys long time ago, since it is
not so easy to enter such long strings with numbers and letters on a
smartphone.

I've now changed ALL of your updatekeys for ALL of your 6 machines to
numbers only, because all of them still had this old format:

This is your new updatekey for ALL of your machines:

UpdateKey:   1029384756

So you now would be able to use the android APP, but you also may need
to change the update key on your other machines with the lico-update.sh
script (use -i for this).

Best regards
Alex





Am 24.05.2015 um 04:05 schrieb Linux-Ham:
> I have installed Lico-update for Android on CM 12.1 and unable to enter
> the Machine-updatekey due to after entering the ID of the machine from
> my profile I am just left with a number pad and unable to enter the
> alphanumeric Machine-updatekey.
> 
> I have tried manually adding the Machine-updatekey to the
> /storage/emulated/data/com.linuxcounter.lico_update_003/.linuxcounter
> file but it still fails to show nor is it deleted from the said file
> either., as you can see from image below.
> 
> screenshot_2015-05-24-11-34-13
> <https://cloud.githubusercontent.com/assets/583652/7786376/efd3d750-0208-11e5-9ac8-4862b4a1bb03.png>
> 
> screenshot_2015-05-24-11-31-04
> <https://cloud.githubusercontent.com/assets/583652/7786374/a82ac7f6-0208-11e5-94f0-d4621dfcf87b.png>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexloehner/linuxcounter-update-examples/issues/4>.
> 

-- 
Best regards
ALEXANDER 'CRIZ' LÖHNER

Burgstr. 4d
D-78351 Bodman-Ludwigsafen
Germany

info: http://adf.ly/1Fo1it
portfolio: http://adf.ly/1Fo1sN
email: alex.loehner@linux.com
mobile: +49 151 234 620 80
facebook: http://adf.ly/1Fo1xl
google+: http://adf.ly/1Fo22K

icq: #43293804
msn: dma147@web.de
skype: alexloehner

homepage1: http://adf.ly/1FnA7P (Linux Counter)
homepage2: http://adf.ly/1Fo28d (APBoard)

https://linuxcounter.net/user/249600

_DONATE TO THE NEW LINUX COUNTER PROJECT:_
 --> http://adf.ly/1Fo2JS

**Comment by Linux-Ham** [comment]
thanks, added the new updatekey but the phone still not updated to the server device '444525' not updated since '2014-01-26'

I have added a debug log over at https://github.com/alexloehner/linuxcounter.android.app/issues/3 cause that problem I seem to be having.

Also be nice if you can make the connections of device to server via SSL than just plain http, noticed that in the log you just using http

**Comment by alexloehner** [comment]
@Linux-Ham I've just released a new version that fixes some major problems with older android versions. Please update and test it. 

SSL on the API will come, when I have enough money to buy one.  :-P
Donations are VERY welcome.  -> https://www.linuxcounter.net/donations

**Comment by Linux-Ham** [comment]
I running the 0.0.6 version and it has updated on the server, I have catlog running monitoring the app for 24 hours or so to make sure it auto updates when meant to etc ;)

when I have a spare few AUD I will make donation, just going through rough patch at moment with bills etc being it near end financial year here, but thanks for all the great work you have put in thus far =)

**Comment by alexloehner** [comment]
Great! ;)
